django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from myapp.views import match_view

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^match_view/', match_view, name='match_view'),
)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Match(models.Model):
	name=models.CharField(max_length=100)
	created_by=models.ForeignKey(User)
	is_active = models.BooleanField(default=True)
	def __unicode__(self):
		return str(self.name)



class Links(models.Model):
	link=models.CharField(max_length=500)
	match = models.ForeignKey(Match)
	team1odd=models.FloatField(default=1.0)
	team2odd=models.FloatField(default=1.0)
	time_left=models.CharField(max_length=500,null=True,blank=True)
	is_active = models.BooleanField(default=True)
	linktype = models.CharField(max_length=10, choices=(('d2l', 'dota2lounge'), ('vpd', 'vpgame dota'), ('vpp', 'vpgame p coins'), ('d2byd', 'dota 2 bestyolo dota'), ('d2byc', 'dota 2 bestyolo csgo'),('d2t', 'dota 2 top'),('nxt', 'nxtgame'),),null=True, blank=True)
	reverse = models.BooleanField(default=False)


	def __unicode__(self):
		return str(self.link)

myapp/views.py
from django.shortcuts import render

from myapp.models import Match,Links
# Create your views here.
from django.contrib.auth.decorators import login_required


def match_view(request):
    active_match=Match.objects.filter(is_active=True).prefetch_related('links_set')
    
    for match in active_match:
    	print match.name
    	for link in match.links_set.all():
    		print link


    return render(request, 'match.html', {"match": active_match})

myapp/templates/match.html
<center><h1>Active matches</h1></center> <br>



<html>
<head>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script> 



<script>

var elements = document.getElementsByClassName("class-1");
for (var i = 0, len = elements.length; i < len; i++) {
    // elements[i].style ...
}

</script>
<script>


function createtable(a) {
    console.log(a)

    var matchid=String(a);
    console.log(matchid)

    var elements = document.getElementsByClassName(matchid.concat(" teama"));

    console.log(elements)

    // for (var j = 0; j < col1.length; j++) {  
    //     if (j % 2 == 0) {
    //         document.write("<tr><td>" + col1[j] + " </td>");
    //         document.write("<td>" + col2[j] + "</td></tr>");
    //     } else {
    //         document.write("<tr  bgcolor='#aeb2bf'><td>" + col1[j] + " </td>");
    //         document.write("<td>" + col2[j] + "</td></tr1>");
    //     }
    // }
}
</script>

    <script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.1.js"></script>
    <script>
var socket = io.connect('http://128.199.245.204:3000/');

      socket.on('chat message', function(msg){
        var partsOfStr = msg.split(',');
        console.log(partsOfStr[0])
        x=document.getElementsByClassName(partsOfStr[0]);  // Find the elements
    for(var i = 0; i < x.length; i++){
    x[i].innerText=partsOfStr[1];    // Change the content
    }
      });
    </script>
</head>
<body>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
.highest{
    background-color:Red;
}



.lowest{
    background-color:Yellow;
}



</style>

{% for row in match %}
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><b>{{ row.name }}</b></div>
  <div class="panel-body">
    <p>
        <script>
          createtable({{ row.pk }});
        </script>

    </p>
  </div>

  <!-- Table -->
  <table class="table" id="mytable">



<tr>
<th>
Site_name

</th>

{% for link in row.links_set.all %}

<th>
<a href="{{ link.link }}" target="_blank">{{ link.get_linktype_display }} </a>
</th>
{% endfor %}
</tr>

<tr>
<th>
Team 1 odds
</th>
{% for link in row.links_set.all %}

{% if link.reverse %}
<td class="{{ row.pk }}.teamb.{{ link.linktype }}">
{{ link.team2odd }}
</td>

{% else %}


{% endif %}



{% endfor %}
</tr>

<tr>
<th>
Team 2 odds
</th>
{% for link in row.links_set.all %}

{% if link.reverse %}
<td class="{{ row.pk }}.teama.{{ link.linktype }}">
{{ link.team1odd }}
</td>

{% else %}

<td class="{{ row.pk }}.teamb.{{ link.linktype }}">
{{ link.team2odd }}
</td>

{% endif %}


{% endfor %}
</tr>

<tr>
<th>
time left
</th>
{% for link in row.links_set.all %}

<td class="{{ row.pk }}.time.{{ link.linktype }}">
{{ link.time_left }}
</td>
{% endfor %}
</tr>


  </table>
</div>

{% endfor %}




</body>